version: "3.9"
# Database Postgres
services:
  db:
    image: postgres:latest
    container_name: "postgres"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: db_backend

  # prometheus - Get Metrics for Monitoring System
  prometheus:
    image: prom/prometheus:latest
    #image: prom/prometheus-linux-arm64:v2.40.2
    container_name: "prometheus"
    user: root
    volumes:
      - "./etc/prometheus/:/etc/prometheus/"
      - "./var/prometheus/prometheus_data:/prometheus"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-lifecycle"
    ports:
      - "9090:9090"

  # Grafana - Graphical data visualization
  grafana:
    image: grafana/grafana:latest
    container_name: "grafana"
    user: root
    ports:
      - "3000:3000"
    volumes:
      - "./var/grafana/grafana_data:/var/lib/grafana"
      - "./etc/grafana/provisioning/:/etc/grafana/provisioning/"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=foobar
      - GF_USERS_ALLOW_SIGN_UP=false

  # AlertManager - Send Alert Log Notification to Slack
  alertmanager:
      image: prom/alertmanager:latest
      container_name: "alertmanager"
      ports:
        - 9093:9093
      volumes:
        - ./etc/alertmanager/:/etc/alertmanager/
      command:
        - "--config.file=/etc/alertmanager/config.yml"
        - "--storage.path=/alertmanager"

  # Portainer - UI Docker Container
  portainer:
    image: portainer/portainer-ce:latest
    container_name: "portainer"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - 9000:9000