COMPANY.SERVICE:
  NAME: "COMPANY APP"
  HOST: "0.0.0.0"
  PORT: 3000
  SERVER_READ_TIMEOUT: 60

USER.SERVICE:
  NAME: "USER APP"
  HOST: "0.0.0.0"
  PORT: 3001
  SERVER_READ_TIMEOUT: 60

DB:
  ADDRESS: 127.0.0.1
  PORT: 5432
  USERNAME: postgres
  PASSWORD: "123456"
  DATABASE: "db_backend"

JWT:
  TOKEN_KEY: "laksdjflkasjfwj92jfslj2qu0-9apsoifjk"
