SERVER:
  VERSION: "1.0.111"

PRODUCT.SERVICE:
  HOST: "0.0.0.0"
  PORT: 3010
  SERVER_READ_TIMEOUT: 60

REGION.SERVICE:
  HOST: "0.0.0.0"
  PORT: 3011
  SERVER_READ_TIMEOUT: 60

TRANSACTION.SERVICE:
  HOST: "0.0.0.0"
  PORT: 3012
  SERVER_READ_TIMEOUT: 60

USER.SERVICE:
  HOST: "0.0.0.0"
  PORT: 3013
  SERVER_READ_TIMEOUT: 60

DB:
  TYPE: "postgres"
  ADDRESS: 127.0.0.1
  PORT: 5432
  USERNAME: postgres
  PASSWORD: "123456"
  DATABASE: "db_backend"

sonar:
  projectKey: Golang-Backend-Base-Project
  projectName: Golang-Backend-Base-Project
  projectVersion: 1.0
  sources: .
  language: go
  sourceEncoding: UTF-8
  host.url: http://localhost:9191
  login: d1001350590e628c92a101f0d5d75335ee8581ee
