SERVER:
  VERSION: "1.0.111"

PRODUCT.SERVICE:
  HOST: "0.0.0.0"
  PORT: 3000
  SERVER_READ_TIMEOUT: 60

TRANSACTION.SERVICE:
  HOST: "0.0.0.0"
  PORT: 3001
  SERVER_READ_TIMEOUT: 60

USER.SERVICE:
  HOST: "0.0.0.0"
  PORT: 3002
  SERVER_READ_TIMEOUT: 60

DB:
  ADDRESS: 127.0.0.1
  PORT: 5432
  USERNAME: postgres
  PASSWORD: "123456"
  DATABASE: "db_backend"

JWT:
  TOKEN_KEY: ""
