apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1-deployment
  labels:
    app: service1
spec:
  replicas: 3 # Adjust the number of desired replicas
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
        - name: service1
          image: your-registry/service1:latest # Replace with your Docker image location
          ports:
            - containerPort: 8080 # Match the port exposed in your Dockerfile
---
apiVersion: v1
kind: Service
metadata:
  name: service1-service
spec:
  selector:
    app: service1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 # Match the port exposed in your Dockerfile
  type: LoadBalancer # Use "LoadBalancer" for cloud providers that support it
