basePath: /api/v1
definitions:
  models.CreateProductRequestDTO:
    properties:
      description:
        type: string
      name:
        type: string
      stock:
        type: integer
    type: object
  utils.ErrorResponse:
    properties:
      code:
        type: integer
      errors: {}
      instance:
        type: string
      status:
        type: string
      traceId:
        type: string
    type: object
  utils.Response:
    properties:
      code:
        type: integer
      data: {}
      status:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: This is a sample swagger for Fiber
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Fiber Example API
  version: "2.0"
paths:
  /:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of server.
      tags:
      - root
  /api/v1/product:
    post:
      consumes:
      - application/json
      description: Create a new product with the provided request data
      parameters:
      - description: Request body containing product details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.CreateProductRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Create a new product
      tags:
      - Product
schemes:
- http
- https
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
