definitions:
  models.CreateCompanyRequestDTO:
    properties:
      description:
        type: string
      name:
        type: string
      website:
        type: string
    type: object
  utils.ErrorResponse:
    properties:
      code:
        type: integer
      errors: {}
      instance:
        type: string
      status:
        type: string
      traceId:
        type: string
    type: object
  utils.Response:
    properties:
      code:
        type: integer
      data: {}
      status:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/company:
    post:
      consumes:
      - application/json
      description: Create a new service.product with the provided request data
      parameters:
      - description: Request body containing service.product details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.CreateCompanyRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: Create a new service.product
      tags:
      - companies
swagger: "2.0"
