name: Go Application CI/CD

on:
  pull_request:
    branches: [ main ]

  push:
    branches: [ main ]

jobs:

  build:
    name: Automation Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

#    test:
#    name: Automation Unit Test
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#
#      - name: Check out code into the Go module directory
#        uses: actions/checkout@v2
#
#      - name: Set up Go
#        uses: actions/setup-go@v2
#        with:
#          go-version: 1.20
#
#      - name: Test
#        run: go test -v ./...

#    deploy:
#    name: Automation Deploy
#    needs: test
#    runs-on: ubuntu-latest
#    steps:
#
#      - name: Check out code
#        uses: actions/checkout@v2
#
#      - name: Install SSH key
#        uses: webfactory/ssh-agent@v0.5.3
#        with:
#          ssh-private-key: ${{" secrets.SSH_PRIVATE_KEY" }}
#
#      - name: Deploy to server
#        run: |
#          ssh user@your-server-ip "cd /path/to/your/app && git pull"

  sonarCloudTrigger:
    needs: build
    name: SonarCloud Automation Static Code Analysis & Code Review
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@master
      - name: Download code coverage results
        uses: actions/download-artifact@v3
        with:
          name: code-coverage-report
          path: bin
      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
