name: Go Application CI/CD

on:
  pull_request:
    branches: [ main ]

  push:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Get dependencies
        run: go get -v -d ./...

      - name: Build
        run: go build -v .

#  test:
#    name: Test
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#
#      - name: Check out code into the Go module directory
#        uses: actions/checkout@v2
#
#      - name: Set up Go
#        uses: actions/setup-go@v2
#        with:
#          go-version: 1.20
#
#      - name: Test
#        run: go test -v ./...

#  deploy:
#    name: Deploy
#    needs: test
#    runs-on: ubuntu-latest
#    steps:
#
#      - name: Check out code
#        uses: actions/checkout@v2
#
#      - name: Install SSH key
#        uses: webfactory/ssh-agent@v0.5.3
#        with:
#          ssh-private-key: ${{" secrets.SSH_PRIVATE_KEY" }}
#
#      - name: Deploy to server
#        run: |
#          ssh user@your-server-ip "cd /path/to/your/app && git pull"

  sonarCloudTrigger:
    needs: build
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@master
      - name: Download code coverage results
        uses: actions/download-artifact@v3
        with:
          name: code-coverage-report
          path: bin
      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}