name: Go Application CI/CD Production

on:
  pull_request:
    branches: [ main ]

  push:
    branches: [ main ]

jobs:

  build:
    name: Automation Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Build
        run: go build -v ./...

  test:
    name: Automation Unit Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Test
        run: go test -v ./...

  deploy:
    name: Automation Deploy
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

#      - name: Install SSH key
#        uses: webfactory/ssh-agent@v0.5.3
#        with:
#          ssh-private-key: ${{" secrets.SSH_PRIVATE_KEY" }}
#
#      - name: Deploy to server
#        run: |
#          ssh user@your-server-ip "cd /path/to/your/app && git pull"

  integrationTest:
    needs: test
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      - run: echo Should run integration tests.

  sonarCloudTrigger:
    needs: [test,integrationTest]
    name: SonarCloud Code Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@master
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v1.9.1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}